import { BlogPost } from '../blogs';

export const architecturePosts: BlogPost[] = [
  {
    id: "post-4",
    slug: "mastering-register-stack-vm-architecture",
    title: "Mastering Register-Stack VM Architecture",
    category: "Architecture",
    author: "VM & Runtime Team",
    date: "July 15, 2026",
    readingTime: "8 min read",
    coverImage: "/blog_vm_architecture.png",
    excerpt: "Deep dive into Quantum's hybrid register-stack virtual machine, instruction dispatch loops, CallFrame structures, and fast local variable offsets.",
    content: [
      {
        type: "paragraph",
        value: "Virtual machines generally fall into two pure camps: stack-based (like Java bytecode or Python) and register-based (like LuaJIT or Dalvik). Quantum bridges both concepts using a **register-stack hybrid execution engine** built directly around `CallFrame` stacks and flat bytecode instruction chunks."
      },
      {
        type: "heading",
        value: { level: 2, text: "1. The CallFrame Architecture" }
      },
      {
        type: "paragraph",
        value: "The VM (`src/vm/`) is built around a CallFrame stack. Each frame holds a Closure (the compiled chunk + captured upvalues), an instruction pointer, and a stack base offset for local variables:"
      },
      {
        type: "code",
        value: {
          language: "cpp",
          code: `struct CallFrame {
    std::shared_ptr<Closure> closure; // Compiled chunk + upvalue vector
    size_t ip;                        // Instruction pointer into closure->chunk->code
    size_t stackBase;                 // Offset index where local variables start on value stack
};`
        }
      },
      {
        type: "heading",
        value: { level: 2, text: "2. The Key Instruction Opcodes" }
      },
      {
        type: "paragraph",
        value: "The compiler emits instructions categorized across core runtime categories:"
      },
      {
        type: "table",
        value: {
          headers: ["Category", "Opcode Names", "Execution Functionality"],
          rows: [
            ["Stack", "LOAD_CONST, LOAD_NIL, LOAD_TRUE, LOAD_FALSE, POP, DUP, SWAP", "Pushes/pops primitives onto value stack"],
            ["Variables", "DEFINE_GLOBAL/LOCAL/CONST, LOAD/STORE_GLOBAL/LOCAL", "Manages scoped variable bindings"],
            ["Upvalues", "LOAD_UPVALUE, STORE_UPVALUE, CLOSE_UPVALUE", "Captures and closes lexical closures"],
            ["Arithmetic", "ADD, SUB, MUL, DIV, MOD, POW, FLOOR_DIV, NEG", "Performs mathematical operations"],
            ["Control Flow", "JUMP, JUMP_IF_FALSE, JUMP_IF_TRUE, LOOP, JUMP_ABSOLUTE", "Branches and handles loop backpatching"],
            ["Functions", "CALL, RETURN, RETURN_NIL, MAKE_FUNCTION, MAKE_CLOSURE", "Manages stack frame creation and function exit"],
            ["Collections", "MAKE_ARRAY, MAKE_DICT, MAKE_TUPLE, GET_INDEX, SET_INDEX", "Instantiation & indexed lookups"]
          ]
        }
      },
      {
        type: "heading",
        value: { level: 2, text: "3. Fast Bytecode Disassembly" }
      },
      {
        type: "paragraph",
        value: "You can inspect the exact instruction stream generated by the single-pass compiler using `--dis` or `--debug` flags:"
      },
      {
        type: "code",
        value: {
          language: "quantum",
          code: `# Dump disassembly and exit
quantum --dis prog.sa

# Disassembly snippet output:
0000 LOAD_CONST    0 ("Quantum Engine")
0002 STORE_LOCAL   1 (title)
0004 LOAD_LOCAL    1
0006 CALL          1 args
0008 RETURN`
        }
      },
      {
        type: "blockquote",
        value: {
          text: "By maintaining fixed stackBase offsets inside each CallFrame, variable lookup operates in O(1) time without hash table overheads during hot loops.",
          cite: "Quantum VM Architecture Doc"
        }
      }
    ]
  },
  {
    id: "post-5",
    slug: "high-performance-memory-management-smart-pointers",
    title: "High-Performance Memory Management with Smart Pointers",
    category: "Performance",
    author: "Systems & Memory Team",
    date: "July 15, 2026",
    readingTime: "7 min read",
    coverImage: "/blog_memory_management.png",
    excerpt: "How Quantum eliminates heavy garbage collection pauses by leveraging std::variant over twelve concrete types and std::shared_ptr for deterministic lifetime management.",
    content: [
      {
        type: "paragraph",
        value: "Traditional dynamically typed scripting languages often suffer from unpredictable Stop-The-World (STW) garbage collection pauses. Quantum takes a different path: **deterministic reference counting via C++ smart pointers and variant type tags**."
      },
      {
        type: "heading",
        value: { level: 2, text: "1. The Twelve Concrete Data Types" }
      },
      {
        type: "paragraph",
        value: "Value representation uses `std::variant` over twelve concrete types defined in `include/Value.h`:"
      },
      {
        type: "code",
        value: {
          language: "cpp",
          code: `// Value representation uses std::variant over twelve concrete types:
// nil · bool · double · string · Array* · Dict* · Closure* ·
// NativeFunc* · Instance* · Class* · BoundMethod* · Pointer*

using QuantumValue = std::variant<
    Nil,
    bool,
    double,
    std::string,
    std::shared_ptr<Array>,
    std::shared_ptr<Dict>,
    std::shared_ptr<Closure>,
    NativeFunc,
    std::shared_ptr<Instance>,
    std::shared_ptr<Class>,
    std::shared_ptr<BoundMethod>,
    std::shared_ptr<QuantumValue> // Pointer*
>;`
        }
      },
      {
        type: "heading",
        value: { level: 2, text: "2. Upvalue Closing & Heap Allocation" }
      },
      {
        type: "paragraph",
        value: "Upvalues capture enclosing scope variables. Initially, an upvalue (`Upvalue::cell`) points directly into the live value stack. When the enclosing stack frame exits, the `CLOSE_UPVALUE` instruction copies the live value into `Upvalue::closed`, allowing closures to persist seamlessly without GC overhead."
      }
    ]
  },
  {
    id: "post-6",
    slug: "building-standalone-executables-quantum-bundler",
    title: "Building Standalone Executables with Quantum Bundler",
    category: "Architecture",
    author: "Toolchain Team",
    date: "July 15, 2026",
    readingTime: "6 min read",
    coverImage: "/blog_bundler.png",
    excerpt: "Learn how quantum.exe compiles source code, serializes bytecode payloads, and appends the binary trailer to produce zero-dependency standalone executables.",
    content: [
      {
        type: "paragraph",
        value: "One of Quantum's hallmark capabilities is turning any `.sa`, `.js`, `.py`, `.c`, or `.cpp` script into a single, zero-dependency executable (`.exe`) that runs on target machines without requiring Node.js, Python, or GCC installed."
      },
      {
        type: "heading",
        value: { level: 2, text: "1. The Serializer & Magic Trailer Payload" }
      },
      {
        type: "paragraph",
        value: "The Serializer (`src/Serializer.cpp`) recursively walks the `Chunk` tree—writing opcodes, operands, line numbers, and nested sub-chunks—into a flat `vector<uint8_t>`. When compiling `quantum app.sa`, it copies `quantum_stub.exe` to `app.exe` and appends:"
      },
      {
        type: "code",
        value: {
          language: "text",
          code: `[ Bare PE Image (quantum_stub.exe) ]
[ Bytecode Payload Vector (vector<uint8_t>) ]
[ Payload Size (uint32_t Little-Endian) ]
[ "QNTM_VM!" Magic Trailer String (8 Bytes) ]`
        }
      },
      {
        type: "paragraph",
        value: "On startup, `app.exe` seeks to the end of its own binary, verifies the `QNTM_VM!` magic header, reads `payloadSize`, deserializes the bytecode `Chunk`, and feeds it directly into the VM."
      }
    ]
  },
  {
    id: "post-7",
    slug: "cryptography-and-secure-scripting-in-quantum",
    title: "Cryptography & Secure Scripting in Quantum",
    category: "Standard Library",
    author: "Security Research Group",
    date: "July 16, 2026",
    readingTime: "6 min read",
    coverImage: "/blog_crypto_security.png",
    excerpt: "Explore Quantum's native cryptographic built-ins: AES-128 ECB encryption, HMAC-SHA256 signatures, entropy checks, and timing-safe string comparison.",
    content: [
      {
        type: "paragraph",
        value: "Security tasks often force developers to pull in heavy third-party C extensions. Quantum embeds industry-standard cryptographic primitives directly into the VM core (`VmNatives.cpp`)."
      },
      {
        type: "heading",
        value: { level: 2, text: "1. Defense Against Timing Side-Channels" }
      },
      {
        type: "paragraph",
        value: "Standard string equality returns early on character mismatch, exposing secret keys to microsecond timing leaks. Quantum provides `constant_time_eq` to guarantee constant evaluation time regardless of input match:"
      },
      {
        type: "code",
        value: {
          language: "quantum",
          code: `# Timing-safe comparison for secret tokens
if constant_time_eq(userToken, validToken):
    print("Authentication successful")`
        }
      },
      {
        type: "heading",
        value: { level: 2, text: "2. Cryptographic Digest Parity" }
      },
      {
        type: "paragraph",
        value: "Native functions return hex digests directly for hashes, HMAC signatures, and secure random byte generation:"
      },
      {
        type: "code",
        value: {
          language: "quantum",
          code: `let token   = secure_random_hex(32)
let hDigest = sha256("payload_data")
let hmac    = hmac_sha256("secret_key", "message")
let cipher  = aes128_ecb_encrypt("16bytekeysecret!", pkcs7_pad("rawText", 16))`
        }
      }
    ]
  }
];
